SELECT T0."DocEntry", T0."U_APPI",
T0."DocNum",
    T0."U_SD",
    T0."U_TRNM",
    T0."U_TPNE",
    T0."U_TPNA",
    T0."U_TPA",
    T0."U_FTY",
    T0."U_VRPY",
    T0."U_VATTO",
    T0."U_TVD",
    T0."U_TVRP",
    T0."U_NVAT",
    T0."U_TAVMN" FROM "SBODEMOGB"."@TNX_VATRP" T0 WHERE T0."U_FTY" = 'A' And T0."UpdateDate"=CURRENT_DATE and T0."UpdateTime">=TO_CHAR(ADD_SECONDS(CURRENT_TIMESTAMP,-60), 'HH24MI')